version: "3"
services:

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Tokyo
    networks:
      - jojoen
  
  app:
    build: ./app
    container_name: app
    tty: true
    ports:
      - "8000:8000"
    networks:
      - jojoen

networks: 
  jojoen: