version: "3"
services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/vue_js:/usr/share/nginx/vue_js
    networks:
      - jojoen
  
  flask:
    build: ./app
    container_name: flask
    volumes:
      - ./app:/var/www/
    networks:
      - jojoen
    tty: true
    ports:
      - "5000:5000"
    command: sh -c "python main.py"

networks: 
  jojoen:
