version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - jojoen
      

  
  django_rest:
    container_name: django_rest
    build:
      context: ./django_rest/
    ports:
      - "8000:8000"
    volumes:
      - ./django_rest/app:/app
    command: bash
    #   sh -c "python manage.py runserver 0.0.0.0:8000"
    tty: true
    networks:
      - jojoen
      
  vue_js:
    container_name: vue_js
    build:
      context: ./vue_js/
    ports:
      - 8080:8080
    volumes:
      - ./vue_js/app:/app
    working_dir: /app
    tty: true
    command: bash -c "cd frontend && npm run serve"
    networks:
      - jojoen

networks:
  jojoen: