version: "3"
services:

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Tokyo
    networks:
      - jojoen
  
  flask:
    build: ./app
    container_name: flask
    networks:
      - jojoen
    tty: true
    ports:
      - "5000:5000"
    command: sh -c "python main.py"

networks: 
  jojoen: