version: "3"
services:

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Tokyo
    networks:
      - jojoen
  
  uvicorn:
    build: ./app
    container_name: uvicorn
    tty: true
    ports:
      - "3031:3031"
    networks:
      - jojoen

networks: 
  jojoen: